apiVersion: v1
kind: Deployment
metadata:
  name: openapi-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: openapi-app
    spec:
      containers:
      - name: openapi-container
        image: opendb/openapi:latest
        ports:
        - containerPort: 80
        env:
        - name: APPINSIGHTS_INSTRUMENTATIONKEY
          value: Your-Own-Application-Insights-Key
---
apiVersion: v1
kind: Service
metadata:
  name: openapi-service
  annotations:
    service.beta.kubernetes.io/external-traffic: OnlyLocal
spec:
  ports:
  - name: http-port
    port: 80
    targetPort: 80
  selector:
    app: openapi-app
  type: LoadBalancer